repositories:
  - rucio_client
  - proxy
  - rucio-daemons
  - cms
  - cc7
  - slc7-installer
  - slc6
  - rucio-server
  - slc7-builder
  - slc5
  - rucio-probes
  - slc6-builder
  - cc8
  - aarch64-slc7-builder
  - frontend
  - reqmgr2ms
  - couchdb
  - cc7-aarch64
  - cmssw
  - dbs
  - reqmgr2
  - workqueue
  - phedex
  - cc7-ppc64le
  - t0_reqmon
  - exporters
  - slc6-base
  - rucio-sync
  - kibana
  - das
  - dbsmigration
  - dqmgui
  - reqmon
  - acdcserver
  - t0wmadatasvc
  - alertscollector
  - confdb
  - elasticsearch-mesos
  - dbs2go
  - reqmgr
  - docker-lxr
  - das2go
  - crabcache
  - crabserver
  - jenkins
  - cmsweb
  - slc7-vanilla
  - mesos-master
  - slc5-builder
  - elasticsearch
  - marathon
  - slc6-installer
  - zookeeper
  - cmsenv-slc6
  - puppet-builder
  - monitor
  - parfullcms
  - mesos-slave
  - logstash
  - mesos-base
  - mesos-dns
  - slc6-vanilla
  - slc5-vanilla
  - cms-docker
  - cmsdist-provider-tester
  - dmwmmon
  - cms-externals
  - sdt-web
  - slc6-externals
  - httpgo
  - sitedb
  - httpsgo
  - cmsmon
  - rucio_dev_env
  - tfaas
  - cmsenv
  - exitcodes
  - nats-sub

teams:
  owners:
    members:
      - cmsblddoc
      - tulamor
      - smuzaffar
      - bbockelm
      
  cmssw:
    permissions:
      slc6-base: write
      cmssw: write
      cmsenv-slc6: write
      slc7-builder: write
      aarch64-slc7-builder: write
      docker-lxr: write
      slc6-builder: write
      jenkins: write
      slc7-installer: write
      cc7-aarch64: write
      slc6: write
      cms: write
      slc5: write
      cc7-ppc64le: write
      cc8: write
      cc7: admin
    members:
      - cmsuser
      - smuzaffar
      - cmsblddoc

  dmwm:
    permissions:
      das: write
      couchdb: write
      nats-sub: write
      cmsweb: write
      frontend: write
      das2go: write
      dbs2go: write
      reqmgr2: write
      exporters: write
      dbs: write
      reqmon: write
      reqmgr: write
      workqueue: write
      rucio_client: write
      rucio_dev_env: write
      rucio-daemons: write
      rucio-server: write
      dqmgui: write
      t0wmadatasvc: write
      dmwmmon: write
      confdb: write
      alertscollector: write
      crabserver: write
      crabcache: write
      acdcserver: write
      dbsmigration: write
      t0_reqmon: write
      phedex: write
      sitedb: write
      cmsmon: write
      httpgo: write
      httpsgo: write
      reqmgr2ms: write
      tfaas: write
      proxy: write
      monitor: write
      rucio-probes: write
      rucio-sync: write
      exitcodes: write
    members:
      - muhammadimranfarooqi
      - cmsblddoc
      - yuyiguo
      - ericvaandering
      - bbockelm
      - veknet