repositories:
  - tuesdayrepo:
      users: write
      addteam: write
  - org0repo:
      users: write
      addteam: write
  - testrepo:
  - cc7:
      testteam: admin
      users: read
  - thursdayrepo:
  - fridayrepo:
      users: admin
teams:
  owners:
    - cmsuser
  users:
    - cmsuser
  testteam:
    - smuzaffar
    - tulamor
  addteam:
  deleteteam:
    - tulamor