repositories:
  - tuesdayrepo
  - org0repo
  - testrepo
  - cc7
  - thursdayrepo
  - fridayrepo
teams:
  owners:
    members:
      - cmsuser

  users:
    permissions:
      fridayrepo: admin
      org0repo: write
      tuesdayrepo: write
      cc7: read
    members:
      - cmsuser
  
  testteam:
    permissions:
      cc7: admin
    members:
      - smuzaffar
      - tulamor

  addteam:
    permissions:
      tuesdayrepo: write
      org0repo: write
    members:

  deleteteam:
    permissions:
    members:
      - tulamor