repositories:
  - fridayrepo
  - tuesdayrepo
  - org0repo
  - testrepo
  - cc7

teams:
  owners:
    members:
      - cmsuser

  users:
    permissions:
      fridayrepo: admin
      org0repo: write
      tuesdayrepo: write
    members:
      - cmsuser
  
  testteam:
    permissions:
      cc7: admin
    members:
      - smuzaffar
      - tulamor

  addteam:
    members:
      tulamor

  deleteteam:
    permissions:
    members: