override: true
push:     true
test:
  script: test.sh
docker: Dockerfile.${tag}
delete_pattern: ${tag}-(2[0-9]{7,})
expires_days: 7
variables:
  CVMFS_UNPACKED: true
multi_arch: true
tags:
  amd64:
    from: cern/cc7-base:latest
    alias: latest
  aarch64:
    from: centos/aarch64:latest
  ppc64le:
    from: ppc64le/centos:7
