override: true
push:     true
test:
  script: test-cmssw.sh
  node:   singularity
delete_pattern: tmp-${tag}-(2[0-9]{7,})
expires_days: 7
daily: d$${now.strftime("%Y%m%d")}
variables:
  CVMFS_UNPACKED: true
from: library/centos:7
docker: Dockerfile.${group}
alias:  ${group}-${daily}
groups:
  amd64:
    tags:
      ${group}-latest:
      ${group}-bootstrap:
        docker: Dockerfile.bootstrap.${group}
        from: cmssw/cc7:${group}
  aarch64:
    tags:
      ${group}-latest:
      ${group}-bootstrap:
        docker: Dockerfile.bootstrap
        from: cmssw/cc7:${group}
  ppc64le:
    tags:
      ${group}-latest:
      ${group}-bootstrap:
        docker: Dockerfile.bootstrap
        from: cmssw/cc7:${group}
