override: true
push:     true
test:
  script: test.sh
docker: Dockerfile.${tag}
delete_pattern: tmp-${tag}-(2[0-9]{7,})
expires_days: 7
daily: d$${now.strftime("%Y%m%d")}
variables:
  CVMFS_UNPACKED: true
from: library/centos:7
tags:
  amd64-latest:
    alias: amd64-${daily}
  aarch64-latest:
    alias: aarch64-${daily}
  ppc64le-latest:
    alias: ppc64le-${daily}
