override: true
push:     false
test:
  script: test.sh
docker: Dockerfile.${tag}
tags:
  amd64:
    from: cern/cc7-base:latest
  aarch64:
    from: centos/aarch64:latest
  ppc64le:
    from: ppc64le/centos:7

