push:   false
tags:
  amd64:
    docker: Dockerfile.${tag}
    from: cern/cc7-base:latest
  aarch64:
    docker: Dockerfile.${tag}
    from: centos/aarch64:latest
  ppc64le:
    docker: Dockerfile.${tag}
    from: ppc64le/centos:7

