push:   true
override: true
delete_pattern: tmp-${group1}.*-(2[0-9]{7,})
expires_days: 7
daily: d$${now.strftime("%Y%m%d")}
architecture: ${group1}
build_context: ..
test:
  script: test-cmssw.sh
  node:   singularity
variables:
  CMS_COMPATIBLE_OS: el8
  DEFAULT_PACKAGES: coreutils-single
  EPEL_PACKAGES:
groups:
  latest:
    alias: ${group1}-${daily}
    from: library/rockylinux:8
    groups:
      x86_64:
        variables:
          EXTRA_PACKAGES: doxygen
        tags:
          ${group1}:
      aarch64:
        tags:
          ${group1}:
