override: false
docker:   Dockerfile
push:     false
unpacked: false
base:     opensciencegrid/osg-wn
daily: m$${now.strftime("%Y%m%d")}
test:
  node:   singularity
  script: test.sh
variables:
  BUILD_DATE: $${now.strftime("%Y%m%d-%H%M%S")}
  EXTRA_PACKAGES: ${packages}
  CVMFS_UNPACKED: ${unpacked}
groups:
  rhle7:
    from: ${base}:3.5-el7
    packages: bzip2
    tags:
      rhel7-latest:
        push: true
        override: true
        alias: rhel7-${daily}
      rhel7:
        unpacked: true
  rhle6:
    from: ${base}:3.4-el6
    packages: compat-readline5
    tags:
      rhel6-latest:
        push: true
        override: true
        alias: rhel6-${daily}
      rhel6:
        unpacked: true

