override: false
docker:   Dockerfile
push:     false
unpacked: false
base:     opensciencegrid/osg-wn
nightly: d$${now.strftime("%Y%m%d")}
monthly: m$${now.strftime("%Y%m")}
variables:
  BUILD_DATE: $${now.strftime("%Y%m%d-%H%M%S")}
test:
  node:   singularity
  script: test.sh
variables:
  EXTRA_PACKAGES: ${packages}
  CVMFS_UNPACKED: ${unpacked}
groups:
  rhle7:
    from: ${base}:3.4-el7
    packages: bzip2
    tags:
      rhel7-${monthly}:
        push: true
      rhel7:
        unpacked: true
  rhle6:
    from: ${base}:3.4-el6
    packages: compat-readline5
    tags:
      rhel6-${monthly}:
        push: true
      rhel6:
        unpacked: true

