override: false
docker:   Dockerfile
base:     opensciencegrid/osg-wn
daily: m$${now.strftime("%Y%m%d")}
delete_pattern: tmp-${tag}-(2[0-9]{7,})
expires_days: 7
test:
  node:   singularity
  script: test-cmssw.sh
variables:
  BUILD_DATE: $${now.strftime("%Y%m%d-%H%M%S")}
  EXTRA_PACKAGES: ${packages}
  CVMFS_UNPACKED: ${unpacked}
push: true
override: true
alias: ${group}-${daily}
groups:
  rhle8:
    tags:
      ${group}-latest:
        from: ${base}:3.5-el8
  rhle7:
    tags:
      ${group}-latest:
        packages: bzip2
        from: ${base}:3.5-el7
  rhle6:
    tags:
      ${group}-latest:
        packages: compat-readline5
        from: ${base}:3.4-el6

