override: false
docker: Dockerfile
push:   false
nightly: $${now.strftime("%Y%m%d")}
monthly: $${now.strftime("%Y%m")}
variables:
  BUILD_DATE: $${now.strftime("%Y%m%d-%H%M%S")}
test:
  node:   singularity
  script: test.sh
variables:
  EXTRA_PACKAGES: ${packages}
groups:
  rhle7:
    from: opensciencegrid/osg-wn:3.4-el7
    packages: bzip2
    tags:
      rhel7-${monthly}:
        push: true
      rhel7:
  rhle6:
    from: opensciencegrid/osg-wn:3.4-el6
    packages: compat-readline5
    tags:
      rhel6-${monthly}:
        push: true
      rhel6:

