docker: Dockerfile
push:   false
base:   opensciencegrid/osg-wn
variables:
  BUILD_BASE: 20191017-0810
test:
  node:   singularity
  script: test.sh
tags:
  rhel7:
    from: ${base}:3.4-el7
    variables:
      EXTRA_PACKAGES: bzip2
  rhel6:
    from: ${base}:3.4-el6
    variables:
      EXTRA_PACKAGES: compat-readline5

