override: false
docker:   Dockerfile.${group}
base:     opensciencegrid/osg-wn
daily: m$${now.strftime("%Y%m%d")}
delete_pattern: tmp-${tag}-(2[0-9]{7,})
expires_days: 7
test:
  node:   singularity
  script: test-cmssw.sh
variables:
  BUILD_DATE: $${now.strftime("%Y%m%d-%H%M%S")}
push: true
override: true
alias: ${group}-${daily}
architecture: amd64
groups:
  rhel8:
    tags:
      ${group}-latest:
        from: ${base}:3.5-el8
      ${group}-cms:
        alias: ${group}-m-${daily}
        MAIL_TO: muzaffar
        from: ${repository}/${name}:alma8-wn
  alma8:
    alias: ${group}-wn-${daily}
    variables:
      SKIP_TESTS: true
      MAIL_TO: muzaffar
    tags:
      ${group}-wn:
        from: library/almalinux:8
        docker: Dockerfile-wn.${group}
  rhel7:
    tags:
      ${group}-latest:
        from: ${base}:3.5-el7
  rhel6:
    tags:
      ${group}-latest:
        from: ${base}:3.4-el6

