docker: Dockerfile
push:   true
override: true
delete_pattern: tmp-${tag}-(2[0-9]{7,})
expires_days: 7
daily: d$${now.strftime("%Y%m%d")}
variables:
  CVMFS_UNPACKED: true
test:
  script: test-cmssw.sh
  node:   singularity
from: library/centos:8
alias: ${group}-${daily}
groups:
  amd64:
    tags:
      ${group}-latest:
  aarch64:
    tags:
      ${group}-latest:
  ppc64le:
    tags:
      ${group}-latest:
